#!/usr/bin/env node
/**
 * build.js — 扫描经书目录，生成 js/data.js 索引
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const CATEGORY_RE = /^(\d{2})-(.+)$/;

function parseInfo(filePath) {
  const text = fs.readFileSync(filePath, 'utf-8');
  const info = {};
  const titleMatch = text.match(/^#\s+(.+)$/m);
  if (titleMatch) info.title = titleMatch[1].trim();
  const fields = {
    translator: /\*\*译者\*\*：(.+)/,
    volumes: /\*\*卷数\*\*：(.+)/,
    category: /\*\*所属部类\*\*：(.+)/,
    brief: /\*\*简介\*\*：(.+)/,
  };
  for (const [key, re] of Object.entries(fields)) {
    const m = text.match(re);
    if (m) info[key] = m[1].trim();
  }
  return info;
}

function getContentFiles(dir) {
  return fs.readdirSync(dir)
    .filter(f => /^\d{3}\.md$/.test(f))
    .sort();
}

function scanScripture(dir, relPath) {
  const infoPath = path.join(dir, 'info.md');
  if (!fs.existsSync(infoPath)) return null;
  const info = parseInfo(infoPath);
  const files = getContentFiles(dir);
  const scripture = { ...info, path: relPath, files };

  // Check for sub-scriptures (e.g. 观世音菩萨普门品, 大势至菩萨念佛圆通章)
  const subs = [];
  for (const entry of fs.readdirSync(dir)) {
    const fullPath = path.join(dir, entry);
    if (fs.statSync(fullPath).isDirectory()) {
      const sub = scanScripture(fullPath, relPath + '/' + entry);
      if (sub) subs.push(sub);
    }
  }
  if (subs.length > 0) scripture.children = subs;
  return scripture;
}

function build() {
  const categories = [];
  const entries = fs.readdirSync(ROOT).sort();

  for (const entry of entries) {
    const match = entry.match(CATEGORY_RE);
    if (!match) continue;
    const catDir = path.join(ROOT, entry);
    if (!fs.statSync(catDir).isDirectory()) continue;

    const [, id, name] = match;
    const scriptures = [];

    for (const sub of fs.readdirSync(catDir).sort()) {
      const subDir = path.join(catDir, sub);
      if (!fs.statSync(subDir).isDirectory()) continue;
      const scripture = scanScripture(subDir, entry + '/' + sub);
      if (scripture) scriptures.push(scripture);
    }

    categories.push({ id, name, dirName: entry, scriptures });
  }

  const output = `// Auto-generated by build.js — do not edit\nwindow.TRIPITAKA_DATA = ${JSON.stringify(categories, null, 2)};\n`;
  const outPath = path.join(ROOT, 'js', 'data.js');
  fs.writeFileSync(outPath, output, 'utf-8');
  console.log(`Generated ${outPath}`);
  console.log(`  ${categories.length} categories, ${categories.reduce((s, c) => s + c.scriptures.length, 0)} scriptures`);
}

build();
